apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: customer
  type: LoadBalancer
  selector:
    app: customer