server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'emil'
    url: jdbc:postgresql://postgres:5432/fraud
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
      enabled: false

zipkin:
  base-url: http://zipkin:9411

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
