spring:
  application:
    name: eureka-server

server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
zipkin:
  base-url: http://zipkin:9411

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
