server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: 'emil'
    url: jdbc:postgresql://localhost:5432/notification
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zipkin:
  base-url: http://localhost:9411

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"